### ISSUE TITLE
Doesn't [^}^{] match on any character that is *not* '{}^'?

### ISSUE THREAD

**Issue by harleypig** [mkaranasou/pyaml_env#11]
https://github.com/mkaranasou/pyaml_env/blob/1ce85018818d5a553c3c499347195a1ec22d47f2/src/pyaml_env/parse_config.py#L37

I'm new to python, but not programming or regexes. I'm confused by this construct:

    default_sep_pattern = r'(' + default_sep + '[^}^{]+)?'

Doesn't that last part allow for any character except '{', '}', or '^'?

If not, what is it doing?

If so, wouldn't '[^}]' be a better construct?

**Comment by mkaranasou** [comment]
Hi, yes, it matches all characters but  `{`, `}`, or `^`. 

In terms of having more flexible default values, since `[^}]` would mean all characters but `}`, I think it would indeed be a better construct. Trying to think whether allowing `{` would backfire somehow :thinking: 
Do you have a case where `{` or `^` needs to be in the default value?

**Comment by harleypig** [comment]
While I can come up with some scenarios, I don't have a specific use case. I was just trying to figure out where my understanding and python differ. There have been a few gotchas, so I'm not assuming anything. :)

Allowing '^' shouldn't be a problem, but the only scenarios I can think of that would allow '{' would have to allow for an escaped '}'. Probably more work than is needed, at least for a 'what if'.
