### ISSUE TITLE
using !ENV always gives a string

### ISSUE THREAD

**Issue by elsucht** [mkaranasou/pyaml_env#26]
Having yml with ENV tag and default values:
```
...
mongodb:
  host: !ENV ${MONGO_HOST:192.168.2.8}
  port: !ENV ${MONGO_PORT:27017}  
  serverSelectionTimeoutMS: 1000
...
```
and loading it with:
```
from pyaml_env import parse_config
appSettings = parse_config('./app/settings/app.yml')
````
gives me:
- a string for host and port (no matter if the ENV variable exists or not)
- a number for serverSelectionTimeoutMS

I would expect that "port" is interpreted as a number too (cause the default value is a number). Otherwise I have to convert every time I use it.
Is there a way to accomplish that?

**Comment by batmanscode** [comment]
How are you converting it now?

**Comment by m3mayllon** [comment]
YAML can autodetect data types. However, it is often necessary to explicitly specify the type using a tag. To force a type, we can prefix the type with a `!!` symbol, for instance `example: !!float 23`. 

However `example: !!float !ENV ${EXAMPLE}` returns an error, making impossible to use such tool. Any thoughts on that?

**Comment by mkaranasou** [comment]
@m3mayllon A great idea! I tried several ways to have this done, but the only way I could do it was via the `tag:yaml.org,2002:` tag which is the translation of `!!` (see [here](https://github.com/yaml/pyyaml/blob/master/lib/yaml/parser.py#L78) )

Can you all take a look at the [PR](https://github.com/mkaranasou/pyaml_env/pull/28) and let me know if this resolves your issue so that I can merge please? :)

**Comment by mkaranasou** [comment]
@m3mayllon thanks for testing this :) 
Yeah, not happy with the aesthetic part too, but I didn't want to introduce a completely new way of doing `!!float` 😬 I mean we could do `!TAG float!! ${...}` `!TAG :float ${...}` or any other variation that is not an existing yaml tag denotation to avoid getting exceptions but... Let me know if you have any other ideas, I'll wait a bit before merging this.
